config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' } do 
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :participants do
    member do
      put :approve
    end
    resources :chatrooms
  end

  get "/find_mentors" => 'mentors#find_mentors'
  resources :mentors do
    put 'add_mentor', param: :mentor_id
    resources :chatrooms
  end

  namespace :api do
    namespace :mobile do
      get 'user_profiles/options' => 'user_profiles#options'
      get 'user_profiles/mentors' => 'user_profiles#mentors'
      get 'user_profiles/participants_for_mentor' => 'user_profiles#participants_for_mentor'
      get 'user_profiles/available_mentors' => 'user_profiles#available_mentors'
      put 'user_profiles/update_mentor_list' => 'user_profiles#update_mentor_list'
      put 'user_profiles/update_participant_list' => 'user_profiles#update_participant_list'
      resources :user_profiles
      resources :users, only: [:update]
      devise_scope :user do
        post 'authenticate' => 'sessions#create', :as => 'login'
        delete 'authenticate' => 'sessions#destroy', :as => 'logout'
      end
      devise_for :users
      get 'messages/new_messages' => 'messages#new_messages'
      resources :messages
    end
  end
  namespace :admin_portal do
    resources :users do
      collection do
        get 'awaiting_access'
        get 'denied_access'
        get 'granted_access'
      end
      member do
        get 'badges'
        put 'grant_access'
        put 'deny_access'
        patch 'upload_new_profile_image'
      end
    end
  end
  get "home/index"
  get "home/minor"

  root to: 'home#index'
end

app/controllers/participants/chatrooms_controller.rb
class Participants::ChatroomsController < ApplicationController
  def show
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
	def index
		@participants = current_user.participants
		@participantsJSON = @participants.to_json
	end

	def show
		@participant = User.find(params[:id])
	end

	def approve
		@participant = User.find(params[:participant_id])
		@user_mentor = UserMentor.find_by(mentor_id: current_user.id, user_id: @participant.id)
		@user_mentor.approve
		redirect_to participants_path
	end
end

app/helpers/participants/chatrooms_helper.rb
module Participants::ChatroomsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-9">
        <h2>My Participants</h2>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <% @participants.each do |mentor| %>
            <div class="col-lg-4">
                <div class="contact-box">
                    <a href="<%= url_for :controller => 'participants', :action => 'show', id: mentor.id %>">
                    <div class="col-sm-4">
                        <div class="text-center">
                            <% if mentor.user_profile&.user_profile_image&.image_path %>
                                <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= mentor.user_profile&.user_profile_image&.image_path %>">
                            <% else %>
                                <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('no_image.png') %>">
                            <% end %>
                            <div class="m-t-xs font-bold"><%= mentor.user_profile&.job_title %></div>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <h3><strong><%= mentor.name %></strong></h3>
                        <p><%= mentor.email %></p>
                        <address>
                                <%= mentor.user_profile&.address&.address_1 %><br>
                                <%= mentor.user_profile&.address&.address_2 %><br>
                                <%= mentor.user_profile&.address&.city %>, <%= mentor.user_profile&.address&.state %> <%= mentor.user_profile&.address&.zip %><br>
                        </address>
                        <% if !mentor.inverse_user_mentors_association.where(mentor_id: current_user.id).first.approved %>
                            <%= link_to 'Approve Participant', approve_participant_path(current_user, participant_id: mentor.id), {class: 'btn btn-info btn-outline', method: :put} %></td>
                        <% end %>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        <% end %>
    </div>
</div>

<% content_for :javascript do %>

<script type="text/javascript">

$(function () {

    $('.contact-box').each(function () {
        animationHover(this, 'pulse');
    });

});

</script>

<% end %>

app/views/participants/show.html.erb
<div class="wrapper wrapper-content">
<div class="row animated fadeInRight">
    <div class="col-md-4">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Participant</h5>
            </div>
            <div>
                <% if @participant.user_profile&.user_profile_image&.image_path %>
                    <div class="ibox-content no-padding border-left-right">
                        <img alt="image" class="img-responsive" src="<%= @participant.user_profile.user_profile_image.image_path %>">
                    </div>
                <% else %>
                    <div class="ibox-content no-padding border-left-right">
                        <img alt="image" class="img-responsive" src='<%= image_path("no_image.png") %>'>
                    </div>
                <% end %>
                <div class="ibox-content profile-content">
                    <h4><strong><%= @participant.name %></strong></h4>
                    <!-- <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p> -->
                    <p><%= mail_to @participant.email %></p>
                    <h5>
                        About me
                    </h5>
                    <p>
                        <%= @participant.user_profile&.bio %>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Profile</h5>
            </div>
            <div class="ibox-content">
                    <h5>Job Title</h5>
                    <p><%=@participant.user_profile&.job_title%></p>

                    <h5>Office Address</h5>
                    <% if @participant.user_profile&.address %>
                        <address>
                            <%=@participant.user_profile&.address.address_1 if @participant.user_profile&.address %></br>
                            <% if @participant.user_profile&.address && @participant.user_profile&.address.address_2.length > 0 %>
                                <%=@participant.user_profile&.address.address_2%></br>
                            <% end %>
                            <%=@participant.user_profile&.address.city if @participant.user_profile&.address %>, <%=@participant.user_profile&.address.state if @participant.user_profile&.address%>. <%=@participant.user_profile&.address.zip if @participant.user_profile&.address%>
                        </address>
                    <% else %>
                        <p>Unknown</p>
                    <% end %>

                    <h5>Linkedin Profile</h5>
                    <% if @participant.user_profile&.linkedin_profile %>
                        <%= link_to @participant.user_profile.linkedin_profile, @participant.user_profile.linkedin_profile, :target => "_blank" %>
                    <% else %>
                        <p>Unknown</p>
                    <% end %>

                    <h5>Languages</h5>
                    <%= @participant.user_profile&.languages ? @participant.user_profile.languages : 'Unknown' %>

                    <h5>Institutions</h5>
                    <%= @participant.user_profile&.institutions ? @participant.user_profile.institutions : 'Unknown' %>

                    <h5>Technical Expertises</h5>
                    <ol>
                    <% @participant.user_profile&.technical_expertises.each do |te| %>
                        <li><%= te.name %></li>
                    <% end %>
                    </ol>

                    <h5>Interpersonal Support</h5>
                    <ol>
                    <% @participant.user_profile&.interpersonal_supports.each do |te| %>
                        <li><%= te.name %></li>
                    <% end %>
                    </ol>

                    <h5>Career Supports</h5>
                    <ol>
                    <% @participant.user_profile&.career_supports.each do |te| %>
                        <li><%= te.name %></li>
                    <% end %>
                    </ol>



            </div>
        </div>

    </div>
</div>
</div>