config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' } do 
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :participants do
    member do
      put :approve
    end
    resources :chatrooms
  end

  get "/find_mentors" => 'mentors#find_mentors'
  resources :mentors do
    put 'add_mentor', param: :mentor_id
    resources :chatrooms
  end

  namespace :api do
    namespace :mobile do
      get 'user_profiles/options' => 'user_profiles#options'
      get 'user_profiles/mentors' => 'user_profiles#mentors'
      get 'user_profiles/participants_for_mentor' => 'user_profiles#participants_for_mentor'
      get 'user_profiles/available_mentors' => 'user_profiles#available_mentors'
      put 'user_profiles/update_mentor_list' => 'user_profiles#update_mentor_list'
      put 'user_profiles/update_participant_list' => 'user_profiles#update_participant_list'
      resources :user_profiles
      resources :users, only: [:update]
      devise_scope :user do
        post 'authenticate' => 'sessions#create', :as => 'login'
        delete 'authenticate' => 'sessions#destroy', :as => 'logout'
      end
      devise_for :users
      get 'messages/new_messages' => 'messages#new_messages'
      resources :messages
    end
  end
  namespace :admin_portal do
    resources :users do
      collection do
        get 'awaiting_access'
        get 'denied_access'
        get 'granted_access'
      end
      member do
        get 'badges'
        put 'grant_access'
        put 'deny_access'
        patch 'upload_new_profile_image'
      end
    end
  end
  get "home/index"
  get "home/minor"

  root to: 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  include TokenAuthenticatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_save :ensure_authentication_token

  validates :first_name, presence: true
  validates :last_name, presence: true
  # validates :title, presence: true

  has_one :user_profile, :dependent => :destroy
  accepts_nested_attributes_for :user_profile

  has_one :device, :dependent => :destroy
  accepts_nested_attributes_for :device
  
  after_create :add_user_profile

  after_validation :check_errors

  def check_errors
    Rails.logger.info "Errors: #{errors.full_messages}"
  end

  # has_many :mentors, :through => :user_mentors, :source => :user
  
  has_many :user_mentors_association, :class_name => "UserMentor", :foreign_key => :mentor_id
  has_many :participants, :through => :user_mentors_association, :source => :user
  has_many :inverse_user_mentors_association, :class_name => "UserMentor", :foreign_key => :user_id
  has_many :mentors, :through => :inverse_user_mentors_association, :source => :mentor

  has_many :messages
  has_many :sent_messages, :class_name => "Message", :foreign_key => :from_user_id
  has_many :received_messages, :class_name => "Message", :foreign_key => :to_user_id


  def self.admins
    admin_role = Role.find_by(:name => "Admin")
    User.joins(:user_profile).where(:user_profiles => { :role_id => admin_role.id })
  end

  def self.mentors
    mentor_role = Role.find_by(:name => "Mentor")
    User.joins(:user_profile).where(:user_profiles => { :role_id => mentor_role.id })
  end

  def self.participants
    participant_role = Role.find_by(:name => "Participant")
    User.joins(:user_profile).where(:user_profiles => { :role_id => participant_role.id })
  end


  def add_user_profile
    u = UserProfile.create! :user_id => id
    d = Device.create! :user_id => id, :uuid => SecureRandom.uuid
    save
  end

  def admin?
    admin_role = Role.find_by(name: 'Admin')
    user_profile&.role == admin_role
  end

  def participant?
    participant_role = Role.find_by(:name => "Participant")
    user_profile&.role == participant_role
  end

  def mentor?
    mentor_role = Role.find_by(:name => "Mentor")
    user_profile&.role == mentor_role
  end

  
  def active_for_authentication?
  	super && approved?
  end

  def inactive_message
  	if !approved?
  		:not_approved
  	else
  		super
  	end
  end

  def name
    return "#{self.first_name} #{self.last_name}"
  end

  def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if !recoverable.approved?
      recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
    elsif recoverable.persisted?
      recoverable.send_reset_password_instructions
    end
    recoverable
  end

  after_create :send_admin_email
  def send_admin_email
    unless created_by_admin
      UserMailer.new_user_waiting_for_approval(self).deliver
    end
  end

  include AASM  
  aasm :access_state, :column => 'access_state' do
    state :awaiting_access, :initial => true
    state :granted_access
    state :denied_access

    event :grant_access do
      transitions :to => :granted_access, :after => Proc.new {|*args|
      	self.approved = true
        UserMailer.access_granted(self).deliver
      }
    end

    event :deny_access do
      transitions :to => :denied_access, :after => Proc.new {|*args|
      	self.approved = false
        UserMailer.access_denied(self).deliver
      }
    end
  end

  def available_mentors
    mentor_role_id = Role.find_by(name: "Mentor").id
    available_mentors = User.joins(:user_profile).where(:user_profiles => { :role_id => mentor_role_id})
    @mentors = available_mentors.where.not(id: self.mentor_ids)
  end

  def completion_rate
    total = 13.0
    count = 0
    count += user_profile.employee_number.nil? || user_profile.employee_number.blank? ? 0 : 1
    count += user_profile.job_title.nil? || user_profile.job_title.blank? ? 0 : 1
    count += user_profile.linkedin_profile.nil? || user_profile.linkedin_profile.blank? ? 0 : 1
    count += user_profile.bio.nil? || user_profile.bio.blank? ? 0 : 1
    count += user_profile.languages.nil? || user_profile.languages.blank? ? 0 : 1
    count += user_profile.institutions.nil? || user_profile.institutions.blank? ? 0 : 1
    count += user_profile.contribution_option_id.nil? ? 0 : 1
    count += user_profile.address&.address_1.nil? ? 0 : 1
    count += user_profile.mentor_detail&.years_of_experience.nil? || user_profile.mentor_detail&.years_of_experience.blank? ? 0 : 1
    count += user_profile.technical_expertises.count == 0 ? 0 : 1
    count += user_profile.interpersonal_supports.count == 0 ? 0 : 1
    count += user_profile.career_supports.count == 0 ? 0 : 1
    count += user_profile.user_profile_image&.image_path ? 0 : 1
    (count / total) * 100
  end


end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
  accepts_nested_attributes_for :user
  
  belongs_to :region, optional: true
  belongs_to :business_line, optional: true
  belongs_to :institution, optional: true

  has_many :project_experiences, :dependent => :destroy
  accepts_nested_attributes_for :project_experiences
  
  has_one :address, :dependent => :destroy
  accepts_nested_attributes_for :address

  has_one :user_profile_image, :dependent => :destroy
  accepts_nested_attributes_for :user_profile_image

  belongs_to :contribution_option, optional: true

  has_and_belongs_to_many :technical_expertises
  has_and_belongs_to_many :interpersonal_supports
  has_and_belongs_to_many :career_supports
  has_one :mentor_detail, :dependent => :destroy
  accepts_nested_attributes_for :mentor_detail
  belongs_to :role, optional: true
  accepts_nested_attributes_for :role
  after_create :add_mentor_detail

  def add_mentor_detail
    mentor = MentorDetail.create! :user_profile_id => id
    save
  end

  def geocoded_state_location
    first = Geocoder.search("#{self.current_lat},#{self.current_long}").first
    first ? first.state : "Unknown"
  end


end

app/controllers/admin_portal/users_controller.rb
class AdminPortal::UsersController < ApplicationController
  include RoleConcerns
  
  def new
    @user = User.new
    @user.build_user_profile
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User has been created"
      redirect_to admin_portal_users_path(:id => @user.id)
    else
      Rails.logger.info @user.errors.full_messages
      message = "User has not been created"
      @user.errors.full_messages.each do |m|
        message += ", #{m}"
      end
      message += '.'
      flash[:error] = message
      render action: "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
    @usersJson = User.all.to_json
  end

  def edit
    @user = User.find(params[:id])
    if !@user.user_profile.user_profile_image
      @user.user_profile.build_user_profile_image
    end
    if !current_user.admin? && (current_user != @user)
      flash[:error] = "You do not have access to that page"
      redirect_to root_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "User has been updated"
      redirect_to admin_portal_users_path(:id => @user.id)
    else
      flash[:error] = "User has not been updated, something went wrong"
      Rails.logger.info @user.errors.full_messages
      render action: "edit"
    end
  end

  def upload_new_profile_image
    @profile = User.find(params[:id]).user_profile
    if @profile.user_profile_image
      @profile.user_profile_image.update_attribute(:short_path, params[:short_path])
    else
      @image = UserProfileImage.create! :short_path => params[:image], :user_profile_id => @profile.id
    end
    @profile.save
  end

  def destroy
    @user.destroy
    flash[:success] = "User deleted"
    render action: 'index'
  end

  def awaiting_access
    @user = User.all
    @users = User.awaiting_access.page(params[:page])
  end
  
  def denied_access
    @user = User.all
    @users = User.denied_access.page(params[:page])
  end
  
  def granted_access
    @user = User.all
    @users = User.granted_access.page(params[:page])
  end
  
  def grant_access
    @user = User.find(params[:id])
    @user.grant_access!
    redirect_to admin_portal_users_path, notice: 'Access Granted'
  end
  
  def deny_access
    @user = User.find(params[:id])
    @user.deny_access!
    redirect_to admin_portal_users_path, alert: 'Access Denied'
  end

  private


  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :title, :password, :password_confirmation, :created_by_admin,
                                 user_profile_attributes: [:id, :contribution_option_id, :role_id, :job_title, :employee_number, :linkedin_profile, :bio, :languages, :institutions,
                                  technical_expertise_ids: [], interpersonal_support_ids: [], career_support_ids: [],
                                  address_attributes: [:id, :address_1, :address_2, :city, :state, :zip],
                                  user_profile_image_attributes: [:id, :short_path]])
  end
end

app/controllers/api/mobile/users/registrations_controller.rb
class Api::Mobile::Users::RegistrationsController < Devise::RegistrationsController
	respond_to :json
	
	def create
		# user = User.new(user_params)
		# if user.save
		# 	render :json=> user.as_json(:auth_token=>user.authentication_token, :email=>user.email), :status=>201
		# 	return
		# else
		# 	warden.custom_failure!
		# 	render :json=> user.errors, :status=>422
		# end
		super
	end

	private

	def after_sign_up_path_for(resource)
		Rails.logger.info resource
	end

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
end

app/controllers/api/mobile/users_controller.rb
class Api::Mobile::UsersController < ApplicationController
	include ApiMobileConcerns


	def update
		if current_user.update_with_password(user_params)
			bypass_sign_in(current_user)
			render :status => 200
		end
	end

	private

	def user_params
		params.require(:user).permit(:current_password, :password, :password_confirmation)
	end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :title, :email, :password, :password_confirmation])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :title, :email, :password, :password_confirmation])
  end

  def after_inactive_sign_up_path_for(resource)
    super(resource)
    flash[:notice] = "Your account has been sent for approval by the site administration"
    respond_to do |format|
      format.html { new_user_session_url }
    end
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin_portal/users_helper.rb
module AdminPortal::UsersHelper
end

app/helpers/api/mobile/users/registrations_helper.rb
module Api::Mobile::Users::RegistrationsHelper
end

app/helpers/api/mobile/users_helper.rb
module Api::Mobile::UsersHelper
end

app/views/admin_portal/users/edit.html.erb
<div class="row">
	<div class="col-lg-8">
		<div class="ibox float-e-margins">
			<div class="ibox-title">
				<h5>New User</h5>
				<div class="ibox-tools">
		            <a class="collapse-link">
		                <i class="fa fa-chevron-up"></i>
		            </a>
		            <a class="close-link">
		                <i class="fa fa-times"></i>
		            </a>
		        </div>
		    </div>
			<div class="ibox-content">
				<%= form_for [:admin_portal, @user], html: { class: 'form-horizontal' } do |f| %>
					<%= f.hidden_field :id %>


					<div class="form-group">
						<%= f.label :email, class: 'col-sm-3 control-label' %>
						<div class="col-sm-6">
							<%= f.text_field :email, class: 'form-control' %>
						</div>
					</div>

					<div class="hr-line-dashed"></div>

					<%= f.fields_for :user_profile, f.object.user_profile do |g| %>
						<div class="form-group">
							<%= g.label :job_title, 'Job Title', class: 'col-sm-3 control-label' %>
							<div class="col-sm-6">
								<%= g.text_field :job_title, class: 'form-control' %>
							</div>
						</div>
						<div class="form-group">
							<%= g.label :role, 'Role', class: 'col-sm-3 control-label' %>
							<div class="col-sm-6">
								<%= g.collection_select :role_id, Role.all, :id, :name, {include_blank: false, label: 'Select Role'}, class: 'form-control' %>
							</div>
						</div>
						<div class="form-group">
							<%= g.label :employee_number, 'Employee Number', class: 'col-sm-3 control-label' %>
							<div class="col-sm-6">
								<%= g.number_field :employee_number, class: 'form-control' %>
							</div>
						</div>

						<%= g.fields_for :address, g.object.address do |h| %>
							<div class="form-group">
								<%= h.label :address_1, 'Address Line 1', class: 'col-sm-3 control-label' %>
								<div class="col-sm-6">
									<%= h.text_field :address_1, class: 'form-control' %>
								</div>
							</div>

							<div class="form-group">
								<%= h.label :address_2, 'Address Line 2', class: 'col-sm-3 control-label' %>
								<div class="col-sm-6">
									<%= h.text_field :address_2, class: 'form-control' %>
								</div>
							</div>

							<div class="form-group">
								<%= h.label :city, 'City', class: 'col-sm-3 control-label' %>
								<div class="col-sm-6">
									<%= h.text_field :city, class: 'form-control' %>
								</div>
							</div>

							<div class="form-group">
								<%= h.label :state, 'State', class: 'col-sm-3 control-label' %>
								<div class="col-sm-6">
									<%= h.text_field :state, class: 'form-control' %>
								</div>
							</div>

							<div class="form-group">
								<%= h.label :zip, 'Zipcode', class: 'col-sm-3 control-label' %>
								<div class="col-sm-6">
									<%= h.text_field :zip, class: 'form-control' %>
								</div>
							</div>
						<% end %>
						<div class="form-group">
							<%= g.label :linkedin_profile, 'Linkedin Profile', class: 'col-sm-3 control-label' %>
							<div class="col-sm-6">
								<%= g.url_field :linkedin_profile, class: 'form-control' %>
							</div>
						</div>
						<div class="form-group">
							<%= g.label :bio, 'Short Bio', class: 'col-sm-3 control-label' %>
							<div class="col-sm-6">
								<%= g.text_area :bio, class: 'form-control', rows: 5 %>
							</div>
						</div>
						<div class="form-group">
							<%= g.label :languages, 'Languages', class: 'col-sm-3 control-label' %>
							<div class="col-sm-6">
								<%= g.text_field :languages, class: 'form-control' %>
							</div>
						</div>
						<div class="form-group">
							<%= g.label :institutions, 'Institutions', class: 'col-sm-3 control-label' %>
							<div class="col-sm-6">
								<%= g.text_field :institutions, class: 'form-control' %>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Technical Expertise</label>
							<div class="col-sm-9">
								<div class="i-checks">
									<%= g.collection_check_boxes(:technical_expertise_ids, TechnicalExpertise.all, :id, :name) do |t| %>
										<br/>
										<label><%= t.check_box %> <%= t.label %></label>
									<% end %>
								</div>
							</div>
						</div>

						<div class="form-group">
							<label class="col-sm-3 control-label">Interpersonal Support</label>
							<div class="col-sm-9">
								<div class="i-checks">
									<%= g.collection_check_boxes(:interpersonal_support_ids, InterpersonalSupport.all, :id, :name) do |t| %>
										<br/>
										<label><%= t.check_box %> <%= t.label %></label>
									<% end %>
								</div>
							</div>
						</div>	

						<div class="form-group">
							<label class="col-sm-3 control-label">Career Support</label>
							<div class="col-sm-9">
								<div class="i-checks">
									<%= g.collection_check_boxes(:career_support_ids, CareerSupport.all, :id, :name) do |t| %>
										<br/>
										<label><%= t.check_box %> <%= t.label %></label>
									<% end %>
								</div>
							</div>
						</div>

						<div class="form-group">
							<label class="col-sm-3 control-label">Contribution Options</label>
							<div class="col-sm-9">
								<div class="i-checks">
									<%= g.collection_radio_buttons(:contribution_option_id, ContributionOption.all, :id, :name) do |t| %>
										<br/>
										<label><%= t.radio_button %> <%= t.label %>: <%= t.object.description %></label>
									<% end %>
								</div>
							</div>
						</div>

					<% end %>

					<div class="form-group">
						<div class="col-sm-4 col-sm-offset-3">
						<%= f.submit 'Submit', class: 'btn btn-primary' %>
					</div>

				<% end %>
			</div>
		</div>
	</div>
</div>
	<div class="col-lg-4">
		<div class="ibox float-e-margins">
			<div class="ibox-title">
				<h5>Profile Picture</h5>
				<div class="ibox-tools">
		            <a class="collapse-link">
		                <i class="fa fa-chevron-up"></i>
		            </a>
		            <a class="close-link">
		                <i class="fa fa-times"></i>
		            </a>
		        </div>
		    </div>
			<div class="ibox-content">
				<%= form_for [:upload_new_profile_image, :admin_portal, @user], html: { class: 'dropzone', id: 'user-profile-image' } do |f| %>
					<!-- <label class="message dz-message">Drop Profile Image Here</label> -->
					<div class="dz-message">Upload Profile Image Here

		            </div>
				<% end %>
				<label>Current Profile Image</label>
				<br />
				<% if @user.user_profile&.user_profile_image&.image_path %>
					<%= image_tag @user.user_profile&.user_profile_image&.image_path, class: 'user-profile-image-preview' %>
				<% end %>
			</div>
		</div>
	</div>
</div>

<% content_for :javascript do %>

	<script type="text/javascript">

	</script>
<% end %>

app/views/admin_portal/users/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-8">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Users</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <input type="text" class="form-control input-sm m-b-xs" id="filter"
                           placeholder="Search in table">

                        <table class="footable table table-stripped" data-page-size="15" data-filter=#filter style="overflow-x: scroll;">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>State</th>
                            <th>Role</th>
                            <th>Profile Percent</th>
                            <th>Location</th>
                            <th>Last Log-In</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <% @users.each do |user| %>
                        <tr class='user-row' data-value='<%= user.id %>'>
                            <td><%= user.name %></td>
                            <td><%= user.email %></td>
                            <td><%= user.access_state.titleize %></td>
                            <td><%= user.user_profile&.role&.name %></td>
                            <td><%= number_to_percentage(user.completion_rate, precision: 0) %></td>
                            <td><%= user.user_profile&.geocoded_state_location ? user.user_profile&.geocoded_state_location : 'Unknown' %></td>
                            <td><%= user.last_sign_in_at&.strftime("%B %d %Y") %></td>
                            <% if user.granted_access? %>
                                <td><%= link_to 'Deny Access', [:deny_access,:admin_portal,user], {class: 'btn btn-danger btn-outline btn-xs', method: :put} %></td>
                            <% elsif user.denied_access? %>
                                <td><%= link_to 'Grant Access', grant_access_admin_portal_user_path(user), class: 'btn btn-xs btn-outline btn-primary', method: :put %></td>
                            <% else %>
                                <td><%= link_to 'Grant Access', grant_access_admin_portal_user_path(user), class: 'btn btn-xs btn-outline btn-primary', method: :put %>
                                <%= link_to 'Deny Access', [:deny_access,:admin_portal,user], {class: 'btn btn-danger btn-outline btn-xs', method: :put} %></td>
                            <% end %>
                        </tr>
                        <% end %>
                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="4">
                                <ul class="pagination pull-right"></ul>
                            </td>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="ibox">
                <div class="ibox-title">
                    <h5 id='user-name'></h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="fullscreen-link">
                            <i class="fa fa-expand"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <table class="table table-stripped">
                        <thead>
                            <tr>
                                <th style="width: 200px"></th>
                                <th style="width: 200px"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td colspan=2><%= link_to 'Add User', [:new, :admin_portal, :user], class: 'btn btn-primary btn-block btn-outline'%>
                                </td>
                            </tr>
                            <tr>
                                <td>First Name:</td>
                                <td id="user-first-name">Name</td>
                            </tr>
                            <tr>
                                <td>Last Name:</td>
                                <td id="user-last-name">Name</td>
                            </tr>
                            <tr>
                                <td>Email:</td>
                                <td id='user-email'>Email</td>
                            </tr>
                            <tr>
                                <td>State:</td>
                                <td id="user-access-state">Awaiting Access</td>
                            </tr>
                            <tr>
                                <td><a href='#' id='user-show' class="btn btn-block btn-outline btn-primary">Show User</td>
                                <td><a href='#' id='user-edit' class="btn btn-block btn-outline btn-primary">Edit User</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<% content_for :javascript do %>

<script type="text/javascript">


$(function() {
    $('.footable').footable();
    renderUser(users[0]);
    $('.user-row').each(function() {
        $(this).on('click', function() {
            renderUserWithId($(this).data('value'));
        });
    })
});

var users = $.parseJSON(<%= @usersJson.inspect.html_safe %>);

function renderUserWithId(id) {
    var user = $.grep(users, function(user) {
        return user.id == id;
    });
    renderUser(user[0]);
}

function renderUser(user) {
    $('#user-name').html(user.first_name + ' ' + user.last_name);
    $('#user-first-name').html(user.first_name);
    $('#user-last-name').html(user.last_name);
    $('#user-email').html(user.email);
    $('#user-access-state').html(titleize(user.access_state));
    $('#user-edit').attr('href', '/admin_portal/users/' + user.id + '/edit');
    $('#user-show').attr('href', '/mentors/' + user.id);
}

function titleize(word) {
    var deletedUnderscoreWord = word.replace(/_/g, ' ');
    var capitalizeEachWord = $.map(deletedUnderscoreWord.split(' '), function(word) {
        return word.charAt(0).toUpperCase() + word.slice(1);
    });
    return capitalizeEachWord.reduce(function(acc, val) {
        return acc + ' ' + val;
    })
}

</script>

<% end %>