config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' } do 
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :participants do
    member do
      put :approve
    end
    resources :chatrooms
  end

  get "/find_mentors" => 'mentors#find_mentors'
  resources :mentors do
    put 'add_mentor', param: :mentor_id
    resources :chatrooms
  end

  namespace :api do
    namespace :mobile do
      get 'user_profiles/options' => 'user_profiles#options'
      get 'user_profiles/mentors' => 'user_profiles#mentors'
      get 'user_profiles/participants_for_mentor' => 'user_profiles#participants_for_mentor'
      get 'user_profiles/available_mentors' => 'user_profiles#available_mentors'
      put 'user_profiles/update_mentor_list' => 'user_profiles#update_mentor_list'
      put 'user_profiles/update_participant_list' => 'user_profiles#update_participant_list'
      resources :user_profiles
      resources :users, only: [:update]
      devise_scope :user do
        post 'authenticate' => 'sessions#create', :as => 'login'
        delete 'authenticate' => 'sessions#destroy', :as => 'logout'
      end
      devise_for :users
      get 'messages/new_messages' => 'messages#new_messages'
      resources :messages
    end
  end
  namespace :admin_portal do
    resources :users do
      collection do
        get 'awaiting_access'
        get 'denied_access'
        get 'granted_access'
      end
      member do
        get 'badges'
        put 'grant_access'
        put 'deny_access'
        patch 'upload_new_profile_image'
      end
    end
  end
  get "home/index"
  get "home/minor"

  root to: 'home#index'
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <div>
        <strong>Copyright</strong> AECOM &copy; 2016-2017
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <span>
                        <%= link_to root_path do %>
                            <img alt="image" id="main-logo" class="img-thumbnail" style="background: transparent; border: none;" src="<%= image_url 'imagine_it_delivered_reverse_300dpi.png' %>"/>
                        <% end %>
                    </span>
                    <% if user_signed_in? %>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold"><%= current_user.name %></strong>
                            </span> <span class="text-muted text-xs block"><%= current_user.title %><b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><%= link_to "Settings", edit_user_registration_path %>
                        </li>
                        <li><%= link_to "Profile", edit_admin_portal_user_path(current_user) %></li>
                        <li class="divider"></li>
                        <li><%= link_to('Log Out', destroy_user_session_path) %>
                        </li>
                    </ul>
                    <% end %>
                </div>
                <div class="logo-element">
                    IN+
                </div>
            </li>
            <!--
            <li>
                <a href="#"><i class="fa fa-sitemap"></i> <span class="nav-label" data-i18n="nav.menulevels">Test</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                   <  <li>
                        <a href="#">Third Level <span class="fa arrow"></span></a>
                        <ul class="nav nav-third-level">
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>

                        </ul>
                    </li>
                </ul>
            </li>
            -->
            <% if current_user %>
                <% if current_user.admin? %>
                    <li>
                        <a href="#"><i class="fa fa-sitemap"></i> <span class="nav-label" data-i18n="nav.menulevels">Admin Portal</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><%= link_to 'Users', admin_portal_users_path %></li>
                        </ul>
                    </li>
                <% end %>
                <% if current_user.admin? || current_user.participant? %>
                    <li>
                        <a href="#"><i class="fa fa-sitemap"></i> <span class="nav-label" data-i18n="nav.menulevels">Mentors</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><%= link_to 'Mentors', mentors_path %></li>
                            <li><%= link_to 'Find Mentors', find_mentors_path %></li>
                        </ul>
                    </li>
                <% end %>

                <% if current_user.admin? || current_user.mentor? %>
                    <li>
                        <a href="#"><i class="fa fa-sitemap"></i> <span class="nav-label" data-i18n="nav.menulevels">Participants</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><%= link_to 'Participants', participants_path %></li>
                        </ul>
                    </li>
                <% end %>
        <% end %>

        </ul>

    </div>
</nav>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" method="post" action="/">
                <div class="form-group">
                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search" />
                </div>
            </form>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <% if user_signed_in? %>
                    <%= link_to(destroy_user_session_path) do %>
                        <i class="fa fa-sign-out"></i> Log out
                    <% end %>
                <% else %>
                    <%= link_to(new_user_session_path) do %>
                        <i class="fa fa-sign-out"></i> Log In
                    <% end %>
                <% end %>
            </li>
        </ul>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Graduate Development Program</title>

    <!-- Include style per-controller - vendor plugins -->
    <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>
    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

</head>
<body>

    <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        <%= render 'layouts/navigation' %>

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Page wrapper -->
            <%= render 'layouts/topnavbar' %>

            <!-- Main view  -->
            <% flash.each do |message_type, message| %>
                <div class="alert alert-<%= message_type %> alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button><%= message %></div>
            <% end %>
            <%= yield %>

            <!-- Footer -->
            <%= render 'layouts/footer' %>
        </div>
        <!-- End page wrapper-->

         <!-- Include javascript per-controller - vendor plugins -->
        <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

        <%= yield :javascript %>
        <%= yield :last_javascripts %>

    </div>
    <!-- End wrapper-->

</body>
</html>